### ISSUE TITLE
Importing plugins in model or world sdf file

### ISSUE THREAD

**Issue by OKsusu1411** [PX4/sitl_gazebo#1029]
Hi i'm trying to simulate standard_vtol at Gazebo garden with several sensors(gps, magnetometer). Unfortunately i don't know how to import those sensor's plugins. currently using is PX4 v1.14.0, and Gazebo garden.

What i want to know about those plugin import line at sdf file
<plugin name='gz::sim::systems::Imu' filename='gz-sim-imu-system'/>
<plugin name='gz::sim::systems::AirPressure' filename='gz-sim-air-pressure-system'/>
First. why can't i change plugin name freely? Everytime i change name, error has occurred after turn on the sitl.
Second. what should i set plugin name and filename for using other plugins (like gps or magnetometer)? 
I just find the plingins cpp file location at ~/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/src. however it doesn't match to filename='gz-sim-imu-system'. so i wonder how can i know 'filename' of plugin and plugin name?
Third. after modifiy plugin cpp in ~/PX4-Autopilot/Tools/simulation/gazebo-classic/sitl_gazebo-classic/src. how do i compile it?

**Comment by hamishwillee** [comment]
Best to start by asking on the support forums, then cross posting an answer here so we can fix the docs for everyone
