### ISSUE TITLE
check sweep (angle between velI and lift-drag-plane)

### ISSUE THREAD

**Issue by mengchaoheng** [PX4/sitl_gazebo#1037]
Why does this line use the asin function instead of acos?

```
  // check sweep (angle between velI and lift-drag-plane)
  double sinSweepAngle = ignition::math::clamp(
      spanwiseI.Dot(velI), minRatio, maxRatio);

  this->sweep = asin(sinSweepAngle);
```

https://github.com/PX4/PX4-SITL_gazebo-classic/blob/f754540e714642fea897445e69a675245bc6306a/src/liftdrag_plugin/liftdrag_plugin.cpp#L252

**Comment by mengchaoheng** [comment]
@pjdewitte @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@mengchaoheng Why should it use cos?

**Comment by mengchaoheng** [comment]
o, I get it. thanks !
