### ISSUE TITLE
Octocopter Thrust Issue

### ISSUE THREAD

**Issue by HYOJUJEONG** [PX4/sitl_gazebo#1050]
Please take a look at my SDF file. The problem I am currently facing is that the 8 motors are rotating differently from each other. Additionally, the drone is not able to take off when given the takeoff command. I have tried to fix it but failed. 

![SharedScreenshot](https://github.com/user-attachments/assets/13668314-703c-4977-a047-f054342da4bc)

[https://github.com/HYOJUJEONG/A4-VAI-test/blob/main/s2000.sdf](url)

**Comment by Jaeyoung-Lim** [comment]
@HYOJUJEONG It is hard to go through the file and debug the problems for you.

Please try to summarize what you have done, and how far you have investigated to find out where the problem is, and ask questions so that we can help you solve the problem.
