### ISSUE TITLE
px4-sitl gazebo sdf

### ISSUE THREAD

**Issue by HYOJUJEONG** [PX4/sitl_gazebo#1052]
I am working on creating an SDF file for an octocopter in PX4-SITL Gazebo. The SDF, airframes, and launch files were initially based on the iris model. Since this is an octocopter, I modified it to have 8 propellers. I also adjusted the parameters as follows:

- mass : 1.0

- ixx, iyy, izz : 0.166667

- maxRotVelocity: 1500
- motorConstant: 0.0001
- momentConstant: 0.06
- rotorDragCoefficient: 0.000175
- rotorVelocitySlowdownSim: 0.0009427
After running the simulation, I receive a message indicating that the vehicle is unstable. Although the vehicle reaches the desired altitude during takeoff, it starts to oscillate. When reviewing the logs, I noticed that the output values for each motor differ significantly.

https://github.com/HYOJUJEONG/A4-VAI-test/blob/main/s2000.sdf

https://review.px4.io/plot_app?log=a755d6c2-673f-46d5-9af8-840343c6b58d

**Comment by Jaeyoung-Lim** [comment]
@HYOJUJEONG You can look at several things

- How realistic are the motor parameters and the moment of inertia?
- Did you retune the attitude controller? If you change the dynamics of the vehicle, you need to retune the controllers in px4
- Where are the oscillations coming from? Have you tried to pinpoint what is causing the oscillations?

**Comment by HYOJUJEONG** [comment]
I corrected the mass and MOI-related errors, which fixed the oscillation issue, but now another problem has emerged where the system drifts sideways. I'm wondering if this can be resolved using PID control.
