### ISSUE TITLE
[Question] Moving models to PX4-gazebo-models

### ISSUE THREAD

**Issue by pulak-gautam** [PX4/sitl_gazebo#1058]
With gazebo classic EOL coming close at Jan '25. Are there any plans to shift the models in this repository to [PX4-gazebo-models](https://github.com/PX4/PX4-gazebo-models)?

**Comment by hamishwillee** [comment]
There is no plan to "shift" the models because they are not compatible. But here are ongoing projects to move Gazebo model support to parity.
