### ISSUE TITLE
Question: Gazebo SITL for fixed-wing plane?

### ISSUE THREAD

**Issue by tdinesh** [PX4/sitl_gazebo#21]
Is there any development for simulating a plane?

**Comment by LorenzMeier** [comment]
There is work being done for a Cessna model. If you want to fly SITL with a plane you can do this already. https://pixhawk.org/dev/simulation/native_sitl#connecting_to_the_simulation_engine

**Comment by tdinesh** [comment]
If I am correct the SITL you mentioned is with JSBSim. I am interested in using Gazebo as the main simulator to use other readily available plugins. Thanks!

**Comment by LorenzMeier** [comment]
Still work in progress: https://github.com/PX4/sitl_gazebo/tree/master/models/cessna

**Comment by tdinesh** [comment]
Thanks! I will keep an eye.
