### ISSUE TITLE
Example of gazebo model for ROS2 rangefinder - libgazebo_ros_ray

### ISSUE THREAD

**Issue by bednarhonza** [PX4/sitl_gazebo#805]
Hi,
I have tried to use the guide posted [here](https://docs.px4.io/master/en/sensor/rangefinders.html). However, it mentions examples only for the ROS1 plugin, but not for ROS2.

ROS2 uses` libgazebo_ros_ray `instead of  ROS1 `libgazebo_lidar_plugin`. An example of ROS2 can be found [here](https://github.com/ros-simulation/gazebo_ros_pkgs/blob/dashing/gazebo_plugins/worlds/gazebo_ros_ray_sensor_demo.world) which works in the simulation, but not with PX4. I did not see the `DISTANCE_SENSOR` message in the `Analyze tools` option of `QGroundControl`.

Is there a way of using `libgazebo_ros_ray` with PX4?

Thank you for your help!

**Comment by Jaeyoung-Lim** [comment]
@bednarhonza You need to create a model that includes a ros2 gazebo plugin. How are you attempting to do this?

**Comment by bednarhonza** [comment]
@Jaeyoung-Lim Yes, we are using our own model. Here is the `sdf` file uploaded as `txt`. [example_model.txt](https://github.com/PX4/PX4-SITL_gazebo/files/7208723/example_model.txt)

**Comment by Jaeyoung-Lim** [comment]
@bednarhonza Great, so you need a ros2 lidar plugin for your model that sends lidar messages to the `gazebo_mavlink_interface_plugin`

The QGC Analyze tools have nothing to do with ROS. It is displaying mavlink messages from px4. If you want to learn more about the simulation architecture, you can look at http://docs.px4.io/master/en/simulation/gazebo.html

**Comment by bednarhonza** [comment]
We have modified the library on our side to communicate with pixhawk. Thank for your help!
