### ISSUE TITLE
Why timeConstantUp is smaller than timeConstantDown

### ISSUE THREAD

**Issue by robin-shaun** [PX4/sitl_gazebo#808]
Hello, in iris.sdf.jinja, the timeConstantUp is smaller than timeConstantDown, which is strange for the BLDC model.
`      <timeConstantUp>0.0125</timeConstantUp>
      <timeConstantDown>0.025</timeConstantDown>`
 I think the  timeConstantUp should be larger than timeConstantDown.

**Comment by Jaeyoung-Lim** [comment]
@robin-shaun Could you elaborate? Usually the time to reach a certain speed is faster, compared to slowing down (without braking).

**Comment by lawrence-cn** [comment]
@Jaeyoung-Lim I have simulated the motor-propeller model with nonlinear aerodynamic torque in the MATLAB and the result shows that the acceleration response is indeed faster than the deceleration response. So using different time constant in two processes is reasonable. If the aerodynamic torque is linear, the acceleration and deceleration responses will be same.
