### ISSUE TITLE
Gust in wind_plugin 

### ISSUE THREAD

**Issue by Gryschock** [PX4/sitl_gazebo#812]
Hi, 

with px4 and ros1 we have a drone flighing in the world. For wind we just added the wind_plugin and konstant wind is working, but influence of the gust. GustVelocity is in m/s and Duration and Start in s? 
![Screenshot from 2021-10-07 12-59-26](https://user-images.githubusercontent.com/38838397/136371642-7a0c8078-85b8-4eef-a560-21ea1bc4f441.png)
What do we have to consider for Gust? 

Thx

**Comment by Jaeyoung-Lim** [comment]
@Gryschock Could you elaborate your question? You can configure the gust with the parameters that are exposed.

If you are curious how each parameters work, you can look at how the gust is being calculated in the `gazebo_wind_plugin`

**Comment by Gryschock** [comment]
@Jaeyoung-Lim 
![SetupWindyWorld](https://user-images.githubusercontent.com/38838397/136571616-d42a00fe-1fa6-4baa-ae53-72ec66b5cad4.png)

I will try to describe, what I am expecting by this settings above in my world file. 
The wind is working, I see in the gazebo simulation an influence. 
And now I want to have a gust, after 60 sec. for 20 sec with direction in y with the same velocity like the const. wind (5 m/s). But I dont see any impact on my UGV, it is just hovering and compensates the const. wind in x-direction. 

So I just dont understand why is normal wind working but the gust not? Have I forgotten something? Do I have to do something the wind_plugin? Or are the parameters wrong? 

Hope this makes it clearer.

Thx

**Comment by Alefunk** [comment]
possibly related: #825

**Comment by WangJintao1998** [comment]
> @Jaeyoung-Lim ![SetupWindyWorld](https://user-images.githubusercontent.com/38838397/136571616-d42a00fe-1fa6-4baa-ae53-72ec66b5cad4.png)
> 
> I will try to describe, what I am expecting by this settings above in my world file. The wind is working, I see in the gazebo simulation an influence. And now I want to have a gust, after 60 sec. for 20 sec with direction in y with the same velocity like the const. wind (5 m/s). But I dont see any impact on my UGV, it is just hovering and compensates the const. wind in x-direction.
> 
> So I just dont understand why is normal wind working but the gust not? Have I forgotten something? Do I have to do something the wind_plugin? Or are the parameters wrong?
> 
> Hope this makes it clearer.
> 
> Thx



> @Jaeyoung-Lim ![SetupWindyWorld](https://user-images.githubusercontent.com/38838397/136571616-d42a00fe-1fa6-4baa-ae53-72ec66b5cad4.png)
> 
> I will try to describe, what I am expecting by this settings above in my world file. The wind is working, I see in the gazebo simulation an influence. And now I want to have a gust, after 60 sec. for 20 sec with direction in y with the same velocity like the const. wind (5 m/s). But I dont see any impact on my UGV, it is just hovering and compensates the const. wind in x-direction.
> 
> So I just dont understand why is normal wind working but the gust not? Have I forgotten something? Do I have to do something the wind_plugin? Or are the parameters wrong?
> 
> Hope this makes it clearer.
> 
> Thx

Did you fix this problem? I have met the same problem.

**Comment by Gryschock** [comment]
Hey, 

actually there is just a miswriting, but should be fixed in the newest version.
