### ISSUE TITLE
Gust in wind plugin permanently set to default value, which is zero, due to a typo

### ISSUE THREAD

**Issue by Alefunk** [PX4/sitl_gazebo#825]
The parameter windGustVelocityMean in the windy.world file has currently no effect because of a typo in the gazebo_wind_plugin: `windGustVeloctiyMean` should be `windGustVelocityMean`

https://github.com/PX4/PX4-SITL_gazebo/blob/master/src/gazebo_wind_plugin.cpp#L65

Easy workaround is to use "windGustVeloctiyMean" as parameter in the world file until this is fixed (or just fix the typo in the .cpp and rebuild).

**Comment by Jaeyoung-Lim** [comment]
@Bearixal Thanks for reporting, Would you be able to make a PR with the fix?
