### ISSUE TITLE
sitl_multiple_vehicle plane spwans inverted 

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/sitl_gazebo#833]
![Screenshot from 2021-12-11 12-19-49](https://user-images.githubusercontent.com/77828768/145667581-2b3f8dfe-2833-4c9d-be96-554465694f72.png)

**Comment by airsimdevdd** [comment]
@Jaeyoung-Lim  sir please help me out

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Please explain how you can reproduce this problem exactly. Your issue does not explain which development environment, which gazebo/PX4 version you are using and which script you are executing to reproduce the failure

Currently I am a bit limited on bandwidth but in the meantime if you can fix the script that would be great: https://github.com/PX4/PX4-Autopilot/blob/master/Tools/gazebo_sitl_multiple_run.sh

**Comment by airsimdevdd** [comment]
I'm using latest PX4 and gazebo version and script  command -"Tools/gazebo_sitl_multiple_run.sh -m plane -n 2"

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Which gazebo version? We currently support gazebo 9 and gazebo 11, which both have their "latest" releases"

you can check with `gazebo --version`

Have you tried looking into the script?

**Comment by airsimdevdd** [comment]
gazebo 9.19.0-1~bionic

**Comment by airsimdevdd** [comment]
yes i looking into script

**Comment by airsimdevdd** [comment]
@Jaeyoung-Lim sir could  you help me out when u are free

**Comment by airsimdevdd** [comment]
problem solved using older px4 version thanks for help @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Using an older version of PX4 is not fixing the problem - reopening

**Comment by airsimdevdd** [comment]
yes there is something issue in script gazebo_sitl_multiple_run.sh

**Comment by airsimdevdd** [comment]
In the script  i changed line 42  to "gz model --spawn-file=/tmp/${MODEL}_${N}.sdf --model-name=${MODEL}_${N} -x 0.0 -y $((3*${N})) -z 1.0 "     works fine

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd I have fixed the issue in https://github.com/PX4/PX4-Autopilot/pull/19063 Thanks!
