### ISSUE TITLE
how to make a custom urdf for multiple uav in gazebo 

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/sitl_gazebo#837]
can anyone guide me for creating totally custom sdf or urdf of uav for multiple_vehicle sitl @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd You can have a look at the models in this repo and how they are templated using [jinja](https://jinja.palletsprojects.com/en/3.0.x/) templates: https://github.com/PX4/PX4-SITL_gazebo/blob/master/models/iris/iris.sdf.jinja

The template models are generated in https://github.com/PX4/PX4-Autopilot/blob/bcd057ac3eb77ca4f1afef532a74843ada1bbe18/Tools/gazebo_sitl_multiple_run.sh#L38

Using these as an example, you should be able to easily create your custom sdf model for multivehicle simulation

**Comment by airsimdevdd** [comment]
I cannot use 
jinja files because jinja files are used by the px4 v1.12.3  and there is problem with that it   spawns uav's
 inverted and crashed image attached  below  ,but 1.11.3 use xacro file which generates the .urdf files at a temp location and spawns good
![Screenshot from 2022-01-21 13-19-46](https://user-images.githubusercontent.com/77828768/150488300-84c910b1-ddf7-4b15-8f17-daa0c22672c5.png)
@Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd You can change the spawn location via the script: https://github.com/PX4/PX4-Autopilot/blob/bcd057ac3eb77ca4f1afef532a74843ada1bbe18/Tools/gazebo_sitl_multiple_run.sh#L42

If you want to use urdf files, then you are free to do so :) However given that gazebo has been moving away from the URDF format, this is no longer supported within PX4

**Comment by airsimdevdd** [comment]
getting error while creating a custom sdf model gazbeo doesnot open mentioned in new issue #838

**Comment by Jaeyoung-Lim** [comment]
Closing since this is no longer related to this repo
