### ISSUE TITLE
Unable to open gazebo after custom sdf model import

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/sitl_gazebo#838]
I am trying to run my custom built model in gazebo but i am getting these errors. I have attached the screenshot. Kindly help.
![Screenshot from 2022-01-22 17-31-58](https://user-images.githubusercontent.com/77828768/150637962-ebd1b8d5-12d5-4b35-9ec3-4a9aafa3ecf3.png)

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd is this happening only on your custom model? Or in general?

If this is with your nodel there is something wrong with your model

**Comment by airsimdevdd** [comment]
it has spawned once. After that it has been showing this error.

**Comment by airsimdevdd** [comment]
@Jaeyoung-Lim what should i do to debug the error?

**Comment by airsimdevdd** [comment]
I tried make clean then cursor  stops at the setting empty.world as default and doesn't load anything up

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Is this only happening for the custom model? or for all models?

> @Jaeyoung-Lim what should i do to debug the error?

You need to check if the sdf generated from your jinja templates are correct

**Comment by airsimdevdd** [comment]
i directly want to use sdf which i converted from urdf file

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd I think you still did not answer the question whether this problem is only happening for your custom model or it is happening for the default models included in PX4.

If it is the latter, you can try with `VERBOSE_SIM=1` to get more verbose outputs and fix your model file

**Comment by airsimdevdd** [comment]
problem is with my model and I , tried with verbose showed some errors

**Comment by airsimdevdd** [comment]
here is the error attached
 
![Screenshot from 2022-01-24 16-05-10](https://user-images.githubusercontent.com/77828768/150767895-4c650c13-2da8-4f52-b7f2-277bebb20bc0.png)

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd I think those errors clearly show you what is wrong with your model :smile: You can fix it now!

**Comment by airsimdevdd** [comment]
i can't clearly understand the problem iam new to this sdf files is joint exists is the problem with the name or wat can u guide me with this .thanks in advance

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Are you sure that there is a joint named as `RudderLeft_joint` or `rotor_4_joint` in your sdf file? 

If you are new to writing sdf files and want to learn how to write a sdf file, you can look at tutorials such as the following
- http://gazebosim.org/tutorials?tut=build_model
- http://gazebosim.org/tutorials?tut=ros_gzplugins

**Comment by airsimdevdd** [comment]
i have generated the urdf from solidworks  then edited it and converted it to sdf , yes i have rudderleft _joint  and rotor_4 joint is rotor_joint

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Please go through the tutorials. `RudderLeft_joint` and `rudderleft _joint` are two different joint names as well as `rotor_4_joint` is not the same as `rotor_joint`

**Comment by airsimdevdd** [comment]
ok thank u i cant understand where to start iam new to this all confused .

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd You can start by going through the sdf/gazebo tutorials, which I posted the link above.

If you want to create your custom model, you need to understand how sdf files work with gazebo before you can integrate your custom model with PX4

**Comment by airsimdevdd** [comment]
solved that errors but struck at  error [Err] [Model.cc:1108] Model[customplane] is attempting to load a plugin, but detected an incorrect plugin type. Plugin filename[libgazebo_airspeed_plugin.so] name[airspeed_plugin]

**Comment by airsimdevdd** [comment]
[Err] [gazebo_motor_model.cpp:198] Aliasing on motor [4] might occur. Consider making smaller simulation time steps or raising the rotor_velocity_slowdown_sim_ param

**Comment by airsimdevdd** [comment]
errrors resolved but my control surfaces are in air and my vehicle is under ground propeller is rotating in air behaving very odd

**Comment by airsimdevdd** [comment]
![Uploading Screenshot from 2022-01-28 16-59-02.png…]()

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd That is a problem of how you have placed the meshes in your sdf file and not a problem related to PX4

**Comment by airsimdevdd** [comment]
does the placement of meshes is with respect to the sequence of the mentioning of the components or the position of the components?? if it is the position of the component then which position should be changed(Visual, collision, or base link position)

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Please go through the sdf documentation / tutorials which can answer your questions in greater detail: https://gazebosim.org/tutorials?tut=build_model

Unfortunately I won't be able to support you with general gazebo related questions

**Comment by bob2299** [comment]
Is there a place ? where Gazebo errors which are popped when we import custom models can be solved . Like ,I'm getting error aliasing on motor may occur , plugin errors .I'm unable to resolve this ? @airsimdevdd  @Jaeyoung-Lim can I get help here ,I'm can't understand what exactly problem is from errors
