### ISSUE TITLE
Wind speed in windy.world doesn't work!

### ISSUE THREAD

**Issue by iamrajee** [PX4/sitl_gazebo#845]
I'm running px4-sitl gazebo with windy.world. I did not change anything inside in world file.  When I take off the drone using QGC, there seems to be no effect to be on the drone. I have also tried to give wind speed in gazebo UI after opening and enable the wind for the model as well but still no luck.

[Here](https://youtu.be/fa1SYOLxop8) is the short video of the issue. Would really appreciate any help :)

**Comment by Jaeyoung-Lim** [comment]
@iamrajee I think there is something wrong on yourside when starting the sim.( I can simulate wind and it works)

Also it is not supposed to work with the gazebo UI since we are using a different topic to simulate wind more accurately.

 Have you tried without using ROS?

```
make px4_sitl gazebo_iris__windy
```

**Comment by iamrajee** [comment]
@Jaeyoung-Lim  Thank you so much for your input. I just tried without ROS as you suggest, I guess it did work(drone fly in slant orientation).

How can I run it with ROS?

I have cloned `PX4-SITL_gazebo` and `PX4-Autopilot` in my `ROS_Workspace/src` and have built using the `catkin_make`. Could that be the reason why I couldn't run with ROS? Do I have to clone `PX4-Autopilot` outside the ROS workspace and then source accordingly?

Thanks in advance for your help.

My system:
Ubuntu 20.04
ROS Noetic

**Comment by Jaeyoung-Lim** [comment]
@iamrajee I would first check if the windy.world is being spawned

**Comment by iamrajee** [comment]
True, world looks different in both cases.

Gazebo windy.world  when launched using ROS
`roslaunch px4 posix_sitl.launch world:=windy.world`
![image](https://user-images.githubusercontent.com/25712145/154890979-91b86877-d5d9-4711-a8d2-ac9ec4c9287c.png)

Gazebo windy.world  when launched without ROS
`make px4_sitl gazebo_iris__windy`
![image](https://user-images.githubusercontent.com/25712145/154891118-a7216f43-5ff3-49b6-a4a4-dc46c09946dc.png)


Moreover, windy.world file is exact the same in both cases.

**Comment by Jaeyoung-Lim** [comment]
You need to pass the full path of the world file, not just the name of the world file.

**Comment by iamrajee** [comment]
Thank you for your prompt response, after giving the full absolute path, it worked. Sorry for the confusion.
