### ISSUE TITLE
 Import a  custom model(fixedwing) in gazebo 

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/sitl_gazebo#847]
I need a sdf file for my custom model and import it to gazebo anybody can do  as full time project @Jaeyoung-Lim

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd If you are looking for a consultant, you can contact someone from the list in https://px4.io/community/consultants/

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Since this issue is not a software related issue, I am closing it.

You can directly hire a consultant or look for people in either the public forum or PX4 slack
