### ISSUE TITLE
Error when building PX-Ardupilot in Ubuntu 20.04

### ISSUE THREAD

**Issue by argenos** [PX4/sitl_gazebo#858]
I'm seeing some errors similar to those reported in #699 at installation time. I am following the instructions from this [wiki](https://github.com/grvcTeam/grvc-ual/wiki/Setup-instructions:-PX4-SITL).

The relevant error that shows up at the `make px4_sitl_default gazebo` step:

```shell
[Err] [Model.cc:1157] Exception occured in the Load function of plugin with name[mavlink_interface] and filename[libgazebo_mavlink_interface.so]. This plugin will not run.
gzserver: /usr/include/boost/smart_ptr/shared_ptr.hpp:734: typename boost::detail::sp_member_access<T>::type boost::shared_ptr<T>::operator->() const [with T = gazebo::event::Connection; typename boost::detail::sp_member_access<T>::type = gazebo::event::Connection*]: Assertion `px != 0' failed.
/home/argen/projects/safemuv/software/code/lux_ws/src/Firmware/Tools/sitl_run.sh: line 93: 1017049 Aborted                 (core dumped) gzserver --verbose "${src_path}/Tools/sitl_gazebo/worlds/${model}.world"
SITL COMMAND: "/home/argen/projects/safemuv/software/code/lux_ws/src/Firmware/build/px4_sitl_default/bin/px4" "/home/argen/projects/safemuv/software/code/lux_ws/src/Firmware"/ROMFS/px4fmu_common -s etc/init.d-posix/rcS -t "/home/argen/projects/safemuv/software/code/lux_ws/src/Firmware"/test_data
INFO  [px4] Creating symlink /home/argen/projects/safemuv/software/code/lux_ws/src/Firmware/ROMFS/px4fmu_common -> /home/argen/projects/safemuv/software/code/lux_ws/src/Firmware/build/px4_sitl_default/tmp/rootfs/etc
0 WARNING: setRealtimeSched failed (not run as root?)
```

On the configuration step of [grvc-ual](https://github.com/grvcTeam/grvc-ual/wiki/How-to-build-and-install-grvc-ual), I've **only** chosen the mavros backend. This combination used to work in Ubuntu 18.04, but might be playing a role in noetic. 

Any pointers as to what I may be missing? I'm not sure how @McKayCyborg solved their issue in #699

**Comment by Jaeyoung-Lim** [comment]
@argenos PX4 is continuously tested in CI and Ubuntu 20.04 is the best supported system. All the SITL testing is run through gazebo11 / Ubuntu 20.04

Therefore, I would say your errors are related to the project grvc-ual using, which I have no knowledge of

**Comment by argenos** [comment]
I'm seeing the same error as in #419 it seems. And I just noticed this could be a duplicate of #850, but I can see the `iris.world` file locally. 

![image](https://user-images.githubusercontent.com/5426039/159972501-db0bc06a-a5f3-4f74-998d-c0c238f9fc67.png)

**Comment by Jaeyoung-Lim** [comment]
@argenos It means you are using an outdated version of PX4. Iris.world doesnt exist anymore: https://github.com/PX4/PX4-SITL_gazebo/tree/master/worlds

**Comment by hamishwillee** [comment]
@Jaeyoung-Lim Hmmm, no one did cleanup. What is the current default world? http://docs.px4.io/main/en/sim_gazebo_classic/#improving-distance-sensor-performance

Are the other iris worlds around, like the hitl_iris.world mentioned in text, and the copter itself, which is mentioned in multiple places? http://docs.px4.io/main/en/sim_gazebo_classic/multi_vehicle_simulation_gazebo.html#video-multiple-multicopter-iris
