### ISSUE TITLE
gzserver: symbol lookup error

### ISSUE THREAD

**Issue by O2KAN** [PX4/sitl_gazebo#859]
gzserver: symbol lookup error: ~/git/simulation/.gitman/px4_firmware/build/px4_sitl_default/build_gazebo/libgazebo_mavlink_interface.so: undefined symbol: _ZN8mav_msgs4msgs17CommandMotorSpeedC1Ev

I have a symbolic lookup error. I couldn't find a solution to fix it. With this error, I can not open the simulation on gazebo correctly.

**Comment by Jaeyoung-Lim** [comment]
@O2KAN How are you building this part of the code?

**Comment by O2KAN** [comment]
I am taking this error for any sitl simulation. make px4_sitl_gazebo,  roslaunch mavros_posix_sitl.launch, roslaunch geometric_controller sitl_trajectory_track_circle.launch. I think you are talking about these lines for building.


![Screenshot from 2022-04-06 11-23-06](https://user-images.githubusercontent.com/39800585/161930391-4dad8e86-f5f5-444c-8881-e93bff3ec026.png)
![Screenshot from 2022-04-06 11-22-35](https://user-images.githubusercontent.com/39800585/161930399-493609f0-1923-42c2-8f55-027c3c518bf7.png)
g

**Comment by Jaeyoung-Lim** [comment]
@O2KAN Try cleaning up your message definitions. (Note that the following commands will remove all your uncommited changes)
```
make distclean
make submodulesupdate
make px4_sitl gazebo
```

**Comment by O2KAN** [comment]
They did not work. I deleted and install everything again. Now the workspace is not building. 
![image](https://user-images.githubusercontent.com/39800585/161983347-046d5c75-dab4-4369-a1dc-3697050bdc41.png)
![image](https://user-images.githubusercontent.com/39800585/161983439-d6ca8eb3-341f-4930-b051-3eb84985f650.png)

**Comment by Jaeyoung-Lim** [comment]
@O2KAN Are you sure you are running ` make px4_sitl_gazebo` ? The mavlink_sitl_gazebo is not under the firmware repo but in some other package `simulation/ros_packages`

**Comment by O2KAN** [comment]
I am getting this error while installing a repository. In that repository px4, mavlink atc. are built-in. When I start the installation they automatically install. 
I applied the same commands you said, it did not work. Later I decided to delete the repository and installed it again. This error is what I get now. 

Thank you for your helping

**Comment by O2KAN** [comment]
This issue is still unresolved. Do you have any idea? 
![image](https://user-images.githubusercontent.com/39800585/163673433-6e42d143-946c-48e6-8b3c-d832465b848a.png)
![image](https://user-images.githubusercontent.com/39800585/163673454-a08c71af-9449-457a-ac2d-3d7a80aeaaea.png)

**Comment by Jaeyoung-Lim** [comment]
@O2KAN please share the full log

Your log you shared shows a different issue with the original issue you have posted

**Comment by O2KAN** [comment]
Actually, they are the same issues, gzserver: symbolic lookup error, just the screenshots are taken from different workspaces.

**Comment by Jaeyoung-Lim** [comment]
@O2KAN please fully explain which workspace is running what. You shouldnt need two workspaces since everything is under the firmware repo.

The error is caused by the faxt that you have two copies of this repo in two separate workspaces

**Comment by O2KAN** [comment]
Yes you are right I don't need two same px4 firmware repo. I installed the other one maybe somehow I can fix the error. 

I don't know but the error was fixed when I tried to use jmsim and install it.  Now working fine. Thank you for your help.
