### ISSUE TITLE
Mavlink Interfacing with Gazebo

### ISSUE THREAD

**Issue by huiyulhy** [PX4/sitl_gazebo#864]
Hi, I'm creating a custom vehicle in SITL to interface with Gazebo for my simulations. Using the same code snippet from Gazebo as the jinja gazebo_plane (but without control surfaces as I just want to test the plugins), the px4-rc.simulator file does not get run (and mavlink interface doesn't start in SITL), but it runs just fine in the gazebo_plane model. 

Command line output for custom vehicle SITL:
![command line custom veh](https://user-images.githubusercontent.com/26198479/169880766-710b08e5-88cd-489d-9a3f-654f30748257.png)

Command line output for gazebo_plane SITL:
![gazebo_plane command line output](https://user-images.githubusercontent.com/26198479/169880914-c275e3de-88e1-4522-92d7-97152cebf166.png)

Comparing the command line outputs between the gazebo_plane SITL and the custom SITL, I can see that TCP port 4560 is not connected for the SITL of the custom vehicle, and is probably the reason why there isn't a SITL mavlink interface. This was the only file change (and link to a custom airframe), hence I was wondering why the TCP port connection was not picked up. 

This is the jinja file section for the custom  #vehicle:
![jinja file ](https://user-images.githubusercontent.com/26198479/169880231-afbf40cc-687b-4c57-a858-bf70d845f552.png)

Any advice is greatly appreciated!

**Comment by Jaeyoung-Lim** [comment]
@huiyulhy I think the problem is probably not related to your sdf model but probably in your airframe configs. (on `1039_`)

Have you compared your custom vehicle airframe config with the default plane model and see if something has not being started. It is hard to tell since you have different parts of the terminal output cut out

**Comment by huiyulhy** [comment]
@Jaeyoung-Lim I copied the parameters (exactly from gazebo_plane) into the custom vehicle airframe config, and tried running the same custom vehicle SITL. 

The first part of the output is the same for the custom airframe, but the parts that differ is shown in the post above. The Mavlink interface was still unable to run

**Comment by Jaeyoung-Lim** [comment]
@huiyulhy The initial screenshot shared looked lile the pareters were not loadong for the custom airframe. Do you have an imu and a mavlink interface in your custom airframe config? Can you do a diff between yours and the plane on the mavlink interface plugin?

**Comment by huiyulhy** [comment]
@Jaeyoung-Lim I realize the issue had not been with mavlink interface. that works fine, turns out that it had been a definition error on one of my links that was preventing this from working. Thanks for helping to debug!
