### ISSUE TITLE
How to set custom spawn location (without roslaunch)

### ISSUE THREAD

**Issue by RG-sw** [PX4/sitl_gazebo#873]
I'm using px4-SITL gazebo _without ROS_ and after a long research I cannot find where/how to modify the model spawn location.
(I'm using Ubuntu 20.04)

Thank you in advance!

**Comment by Jaeyoung-Lim** [comment]
@RG-sw https://github.com/PX4/PX4-Autopilot/blob/0922f003f586ac32d3d0ce08d0a2ad76218b8542/launch/posix_sitl.launch#L44

**Comment by RG-sw** [comment]
@Jaeyoung-Lim Thanks for the fast reply!
I tried to modify the launch file you mentioned but the changes are not shown in Gazebo.
I tried running with `make px4_sitl gazebo` and  `make px4_sitl_default gazebo` .
Am I doing something wrong ?

**Comment by Jaeyoung-Lim** [comment]
@RG-sw Yes, if you are using the make file the spawn location is defined in https://github.com/PX4/PX4-Autopilot/blob/0922f003f586ac32d3d0ce08d0a2ad76218b8542/Tools/sitl_run.sh#L172

**Comment by RG-sw** [comment]
Thank you a lot!
