### ISSUE TITLE
Gazebo message size for Odometry not correct

### ISSUE THREAD

**Issue by ecmnet** [PX4/sitl_gazebo#876]
In the header of the odometer message the size of the message is specified. Adding 'repeating' fields for covariance according to the `odometer.proto` definition, increases the size of the message. However, as the same instance is reused in the publishing loop, covariances are added in each cycle instead of replaced.  

A simple solution to this would be to clear the covariance fields of the message before re-using them, like

`odom_msg.clear_velocity_covariance();
  odom_msg.clear_pose_covariance();`

in `VisionPlugin::OnUpdate` of the `gazebo_vision_plugin.cpp` before filling up the message again.

**Comment by Jaeyoung-Lim** [comment]
@ecmnet Would you be able to create a PR to address this?

**Comment by ecmnet** [comment]
@Jaeyoung-Lim Here you are.

**Comment by Jaeyoung-Lim** [comment]
Fixed in #878
