### ISSUE TITLE
Can we change mavlink tcp port to which gazebo connects ?

### ISSUE THREAD

**Issue by airsimdevdd** [PX4/sitl_gazebo#889]
I want gazebo to connect to different tcp port other than tcp  4560 ,px4 must open 4560 I want to intercept the msgs and redirect it to gazebo

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Yes, you can change the port by configuring the tcp port of the plugin: https://github.com/PX4/PX4-SITL_gazebo/blob/f71680afab60da2d72bcbddbed0b289cd0cd7814/models/iris/iris.sdf.jinja#L453

**Comment by airsimdevdd** [comment]
> @airsimdevdd Yes, you can change the port by configuring the tcp port of the plugin:
> 
> https://github.com/PX4/PX4-SITL_gazebo/blob/f71680afab60da2d72bcbddbed0b289cd0cd7814/models/iris/iris.sdf.jinja#L453

I am launching Gazebo with ros wrappers, I have already changed TCP port of the plugin yet everything remains the same.

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Have you checked if the sdf file generated have the tcp port changes you applied? If not you need to figure out what your ros wrapper is doing with the sdf generation

**Comment by airsimdevdd** [comment]
> @airsimdevdd Have you checked if the sdf file generated have the tcp port changes you applied? If not you need to figure out what your ros wrapper is doing with the sdf generation

Yes I have checked, sdf file does have the same tcp port. Any more suggestions...??

**Comment by Jaeyoung-Lim** [comment]
@airsimdevdd Then it means your change did not get applied? It is not possible that nothing changes if the tcp port has changed in the sdf file and the simulation is using it. The plugin configures the port

**Comment by Jaeyoung-Lim** [comment]
Closing as there was no response
