### ISSUE TITLE
cant compile in ubuntu 20.04

### ISSUE THREAD

**Issue by jorgeneo560** [PX4/sitl_gazebo#912]
i cant compile, theres a lot of problems in this ubuntu version, i was able to fixed the most part but now i am stuck here
<pre>-- install-prefix: /usr
-- cmake build type: RelWithDebInfo
-- Using C++17 standard
-- Found TinyXML: /usr/lib/x86_64-linux-gnu/libtinyxml.so  
-- Checking for module &apos;gstreamer-1.0 &gt;= 1.0&apos;
--   No package &apos;gstreamer-1.0&apos; found
-- Checking for module &apos;gstreamer-base-1.0 &gt;= 1.0&apos;
--   No package &apos;gstreamer-base-1.0&apos; found
-- Checking for module &apos;gstreamer-app-1.0 &gt;= 1.0&apos;
--   No package &apos;gstreamer-app-1.0&apos; found
-- Found GStreamer: GSTREAMER_INCLUDE_DIRS;GSTREAMER_LIBRARIES;GSTREAMER_VERSION;GSTREAMER_BASE_INCLUDE_DIRS;GSTREAMER_BASE_LIBRARIES (Required is at least version &quot;1.0&quot;) 
-- Found unsuitable Qt version &quot;&quot; from NOTFOUND
Qt QTGUI library not found.
Qt QTCORE library not found.
-- Checking for module &apos;OGRE&apos;
--   No package &apos;OGRE&apos; found
<font color="#C01C28">CMake Error at CMakeLists.txt:103 (add_subdirectory):</font>
<font color="#C01C28">  The source directory</font>

<font color="#C01C28">    /home/x/PX4/PX4-SITL_gazebo/external/OpticalFlow</font>

<font color="#C01C28">  does not contain a CMakeLists.txt file.</font>

-- Could NOT find MAVLink (missing: MAVLINK_INCLUDE_DIRS) (found version &quot;2.0&quot;)
-- catkin DISABLED
<font color="#C01C28">CMake Error at /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:230 (message):</font>
<font color="#C01C28">  Could NOT find Protobuf (missing: Protobuf_LIBRARIES Protobuf_INCLUDE_DIR)</font>
<font color="#C01C28">Call Stack (most recent call first):</font>
<font color="#C01C28">  /usr/share/cmake-3.22/Modules/FindPackageHandleStandardArgs.cmake:594 (_FPHSA_FAILURE_MESSAGE)</font>
<font color="#C01C28">  /usr/share/cmake-3.22/Modules/FindProtobuf.cmake:650 (FIND_PACKAGE_HANDLE_STANDARD_ARGS)</font>
<font color="#C01C28">  CMakeLists.txt:145 (find_package)</font>

-- Configuring incomplete, errors occurred!
See also &quot;/home/x/PX4/PX4-SITL_gazebo/build/CMakeFiles/CMakeOutput.log&quot;.
</pre>
dont know what to do, i need to setup a simulation to test flight paths generated with qground

**Comment by tayyabkhalil-313** [comment]
Did you install the dependencies for running the simulation described [here](https://docs.px4.io/main/en/dev_setup/dev_env_linux_ubuntu.html#gazebo-jmavsim-and-nuttx-pixhawk-targets)? Did running the script _ubuntu.sh_ throw up any errors?

**Comment by Jaeyoung-Lim** [comment]
@jorgeneo560 You need to update your submodule

**Comment by Katawann** [comment]
Hi,

I think I have the same issue but building from a docker. 

Error:
```
 Built target HelicopterMixer
-- Building klt_feature_tracker without catkin
-- Building OpticalFlow with OpenCV
-- Could NOT find MAVLink (missing: MAVLINK_INCLUDE_DIRS) (found version "2.0")
-- catkin DISABLED
-- Found Protobuf: /usr/lib/x86_64-linux-gnu/libprotobuf.so;-lpthread (found version "3.6.1") 
-- Gazebo version: 9.12
-- Found GStreamer: adding gst_camera_plugin
-- Found GStreamer: adding gst_video_stream_widget
CMake Error: The following variables are used in this project, but they are set to NOTFOUND.
Please set them or make sure they are set and tested correctly in the CMake files:
_MAVLINK_INCLUDE_DIR
```


The docker file to reproduce:

```
FROM ubuntu:20.04

ENV WORKSPACE_DIR /root
ENV FIRMWARE_DIR ${WORKSPACE_DIR}/PX4-Autopilot

ENV DEBIAN_FRONTEND=noninteractive

RUN apt-get update && \
    apt-get install -y bc \
                       cmake \
                       curl \
                       gazebo9 \
                       git \
                       gcc \
                       gcc-arm-none-eabi \
                       g++ \
                       gstreamer1.0-plugins-bad \
                       gstreamer1.0-plugins-base \
                       gstreamer1.0-plugins-good \
                       gstreamer1.0-plugins-ugly \
                       iproute2 \
                       libeigen3-dev \
                       libgazebo9-dev \
                       libgstreamer-plugins-base1.0-dev \
                       libgstrtspserver-1.0-dev \
                       libopencv-dev \
                       libroscpp-dev \
                       protobuf-compiler \
                       python3-jinja2 \
                       python3-empy \
                       python3-jsonschema \
                       python3-numpy \
                       python3-pip \
                       unzip \
                       xvfb && \
    apt-get -y autoremove && \
    apt-get clean autoclean && \
    rm -rf /var/lib/apt/lists/{apt,dpkg,cache,log} /tmp/* /var/tmp/*

RUN pip install numpy \
                toml \
                pyyaml

RUN pip3 install empy \
                 jinja2 \
                 packaging \
                 pyros-genmsg \
                 toml \
                 pyyaml \
                 kconfiglib

RUN git clone https://github.com/PX4/PX4-Autopilot.git ${FIRMWARE_DIR}
RUN git -C ${FIRMWARE_DIR} checkout tags/v1.13.0
RUN git -C ${FIRMWARE_DIR} submodule update --init --recursive
RUN cd ${FIRMWARE_DIR} && DONT_RUN=1 make px4_sitl gazebo
```

I let you know if I found the issue

**Comment by Jaeyoung-Lim** [comment]
@Katawann I don't think your issue is related.
The builds are checked in the CI, so I suspect there is something wrong specific to your setup.

Why not use the setup script (`Tools/setup/ubuntu.sh`) to install the dependencies?

**Comment by Katawann** [comment]
Indeed... I succeed to do it with an updated dockerfile. Sorry for bringing up the subject again
