### ISSUE TITLE
Iris Drone Parameter: Rotor chord 

### ISSUE THREAD

**Issue by SatoSuga** [PX4/sitl_gazebo#921]
Hi,
I was wondering if there is a rotor description file for the iris drone. 
I'm trying to build a drone model in Simulink which should behave like the Iris model. 
So far, I only found the rotor drag coefficient, but I want to find the rotor chord. 
Can somebody help me?

**Comment by Jaeyoung-Lim** [comment]
@SatoSuga You can look at the motor model source to look at the exact model of the motor: https://github.com/PX4/PX4-SITL_gazebo/blob/56b5508b72f40339448f3525dd4dc51f30512cbd/src/gazebo_motor_model.cpp
