### ISSUE TITLE
<frameName> for different spawned models

### ISSUE THREAD

**Issue by Cavalletta98** [PX4/sitl_gazebo#947]
Hi, i need help with gazebo plugin

`<plugin filename="libgazebo_ros_openni_kinect.so" name="camera_controller">
          <cameraName>camera</cameraName>
          <robotNamespace></robotNamespace>
          <alwaysOn>true</alwaysOn>
          <updateRate>10</updateRate>
          <pointCloudCutoff>0.2</pointCloudCutoff>
          <pointCloudCutoffMax>65.535</pointCloudCutoffMax>
          <imageTopicName>rgb/image_raw</imageTopicName>
          <cameraInfoTopicName>rgb/camera_info</cameraInfoTopicName>
          <depthImageTopicName>depth/image_raw</depthImageTopicName>
          <depthImageCameraInfoTopicName>depth/camera_info</depthImageCameraInfoTopicName>
          <pointCloudTopicName>depth/points</pointCloudTopicName>
          <frameName>camera_link</frameName>
          <distortion_k1>0.0</distortion_k1>
          <distortion_k2>0.0</distortion_k2>
          <distortion_k3>0.0</distortion_k3>
          <distortion_t1>0.0</distortion_t1>
          <distortion_t2>0.0</distortion_t2>
        </plugin>`

I need the `<frameName>` tag usable with namespace in order to have different frame name for each model that i will spawan.
Can someone could help me?

**Comment by Jaeyoung-Lim** [comment]
Fixed in https://github.com/PX4/PX4-SITL_gazebo-classic/pull/941
