### ISSUE TITLE
Can't control Px4 sitl gazebo using MATLAB Simulink.

### ISSUE THREAD

**Issue by Dexter9219** [PX4/sitl_gazebo#964]
Hii there, 
I m a newbie. 

I am trying to control Tailsitter UAV using MATLAB Simulink. I designed a controller in Simulink that gives the command to the actuators (required forces and moments)  via mavros (mavros/actuator_control) but cannot send commands. Please help me.

**Comment by Jaeyoung-Lim** [comment]
@Dexter9219 This repository is a simulation integration of PX4 for Gazebo, and is not related to matlab or simulink.

Please bring this discussion either to the main repo or contact mathworks directly
